language: php
php:
  - 5.5
  - 5.6
  - 7.0
install:
  - composer install
  - composer require php-coveralls/php-coveralls
before_script:
  - mkdir -p build/logs
script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'